version: '3.9'
services:
  grafana:
    build: .
    image: grafana-oss
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
volumes:
  grafana-data:
  grafana-logs:
